# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/csw/Desk/CS202/CPU/simple-cpu/cpu/cpu.srcs/sources_1/ip/IMem/IMem.xci
# IP: The module: 'IMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/csw/Desk/CS202/CPU/simple-cpu/cpu/cpu.srcs/sources_1/ip/IMem/IMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IMem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/csw/Desk/CS202/CPU/simple-cpu/cpu/cpu.srcs/sources_1/ip/IMem/IMem.xci
# IP: The module: 'IMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/csw/Desk/CS202/CPU/simple-cpu/cpu/cpu.srcs/sources_1/ip/IMem/IMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IMem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
